name: Two Six Creative
favicon: null
layout_spectrum: 0.50821
typography_spectrum: 0.15816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000034'
    - '#ffffff'
    - '#ff6005'
    - '#606081'
    - '#dfdfe5'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
